projects:
  ChatAPI:
    schemaPath: ../iOSChatAppAWSAppSync/ChatApp/graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        apiId: 737evs3ivncv7o5zwucqcymwvm
        maxDepth: 2
extensions:
  amplify:
    version: 3
